#!/usr/bin/env bash
# Slack notification on a SUCCESSFUL Cloudflare Workers Builds deploy.
#
# Generated by the /cloudflare-deploy-slack-notify skill. Edit the CONFIG block
# below for your project, commit this file, then wire it into the deploy command
# (see "WIRING" + the required secrets).
#
# WIRING (Cloudflare Dashboard -> your Worker -> Settings -> Build -> Deploy command):
#   Production deploy command:      npx wrangler deploy            && bash .cloudflare/notify-slack.sh
#   Non-production deploy command:  npx wrangler versions upload   && bash .cloudflare/notify-slack.sh
#   (append `&& bash .cloudflare/notify-slack.sh` to whatever deploy command you already use)
#
# Why `&&` + "this script always exits 0":
#   - deploy fails -> `&&` skips notify -> exit = wrangler's failure -> CF marks build FAILED  (ok)
#   - deploy ok    -> notify runs, ALWAYS exits 0 -> CF marks build SUCCESS                    (ok)
#   A Slack/network hiccup must never turn a good deploy red. NEVER wrap the whole deploy
#   command in `|| true` -that would also mask a real deploy failure.
#
# SECRETS (Dashboard -> Settings -> Build -> Variables & Secrets, type = Secret):
#   SLACK_WEBHOOK_URL  (required) - Slack Incoming Webhook (https://hooks.slack.com/services/...).
#                                   Without it this script no-ops (safe for forks / local).
#   CF_API_TOKEN       (optional) - Cloudflare API token, permission
#                                   "Account > Workers Builds Configuration > Read".
#                                   Enables the "commits since previous deploy" list; without it
#                                   the message shows only the HEAD commit.
#
# Runs in the same Workers Builds container as the build (Node + git present, repo at root).
# Keep this file PURE ASCII -emit any non-ASCII via Node (String.fromCharCode). See the skill's
# Pitfalls for why literal/`\u`-escaped bullets break.

set -uo pipefail

# ===================== CONFIG (fill for your project) =====================
ACCOUNT_ID="<ACCOUNT_ID>"            # Cloudflare account id (wrangler.jsonc `account_id`)
SCRIPT_ID="<WORKER_TAG_ID>"          # Worker *tag* (NOT name). GET /accounts/{id}/workers/scripts -> .id
PROD_BRANCH="main"                   # branch that deploys to production
PROD_URL="https://<your-prod-domain>/"
# Staging URL: printf template, %s is replaced by the sanitized branch name.
# Workers Builds branch alias = "<branch>-<worker-name>.<account-subdomain>.workers.dev".
STAGING_URL_FMT="https://%s-<worker-name>.<account-subdomain>.workers.dev/"
# Optional: echo the deployed version string (e.g. parse a generated build-flags file).
# Leave the body as `:` (no-op) to omit the version from the message.
get_version() {
	:
	# Example (Compose/KMP web):
	# sed -nE 's/.*VERSION_NAME[^"]*"([^"]+)".*/\1/p' \
	#   app/build/generated/.../WebBuildFlags.kt 2>/dev/null | head -1 | tr -d '\r'
}
# =========================================================================

WEBHOOK="${SLACK_WEBHOOK_URL:-}"
if [ -z "$WEBHOOK" ]; then
	echo "notify-slack: SLACK_WEBHOOK_URL not set, skipping"
	exit 0
fi

# --- Resolve environment from the branch Workers Builds is building ---------
BRANCH="${WORKERS_CI_BRANCH:-$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)}"
CURRENT_SHA="${WORKERS_CI_COMMIT_SHA:-$(git rev-parse HEAD 2>/dev/null || echo '')}"

if [ "$BRANCH" = "$PROD_BRANCH" ]; then
	ENV_LABEL="Production"
	SITE_URL="$PROD_URL"
	EMOJI=":rocket:"
else
	ENV_LABEL="Staging"
	# Branch alias: lowercase, non-alphanumeric -> '-', collapse repeats, trim.
	ALIAS="$(printf '%s' "$BRANCH" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9' '-' | sed 's/-\{2,\}/-/g; s/^-//; s/-$//')"
	# shellcheck disable=SC2059
	SITE_URL="$(printf "$STAGING_URL_FMT" "$ALIAS")"
	EMOJI=":construction:"
fi

WEB_VERSION="$(get_version 2>/dev/null || true)"
[ -z "$WEB_VERSION" ] && WEB_VERSION=""

# --- Previous deployed commit (PREV) via Cloudflare Builds API --------------
# Newest SUCCESS build on the same branch whose commit != current. The in-flight
# build is not "success" yet, so the newest success = the previous deploy.
PREV_SHA=""
if [ -n "${CF_API_TOKEN:-}" ] && [ -n "$CURRENT_SHA" ] && [ "$SCRIPT_ID" != "<WORKER_TAG_ID>" ]; then
	API_URL="https://api.cloudflare.com/client/v4/accounts/${ACCOUNT_ID}/builds/workers/${SCRIPT_ID}/builds?per_page=50"
	RESP="$(curl -fsS --max-time 15 -H "Authorization: Bearer ${CF_API_TOKEN}" "$API_URL" 2>/dev/null || echo '')"
	if [ -n "$RESP" ]; then
		PREV_SHA="$(printf '%s' "$RESP" | BRANCH="$BRANCH" CURRENT_SHA="$CURRENT_SHA" node -e '
let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{
  try{
    const j=JSON.parse(s), br=process.env.BRANCH, cur=process.env.CURRENT_SHA;
    const ok=(j.result||[]).filter(b=>b&&b.build_outcome==="success"&&b.build_trigger_metadata
      &&b.build_trigger_metadata.branch===br&&b.build_trigger_metadata.commit_hash&&b.build_trigger_metadata.commit_hash!==cur);
    ok.sort((a,b)=>new Date(b.created_on)-new Date(a.created_on));
    process.stdout.write(ok.length?String(ok[0].build_trigger_metadata.commit_hash):"");
  }catch(e){process.stdout.write("");}
});' 2>/dev/null || echo '')"
	fi
fi
# Local smoke override: NOTIFY_FAKE_PREV=<sha> exercises the full range path
# without CF_API_TOKEN (pair with NOTIFY_DRY_RUN=1 to print instead of send).
PREV_SHA="${NOTIFY_FAKE_PREV:-$PREV_SHA}"

# --- Collect the commit list (PREV..CURRENT) -------------------------------
# Workers Builds clones shallow -> deepen history before asking for a range.
if [ -n "$PREV_SHA" ] && ! git cat-file -e "${PREV_SHA}^{commit}" 2>/dev/null; then
	git fetch --deepen=300 2>/dev/null || git fetch --unshallow 2>/dev/null || true
fi

LOG=""
if [ -n "$PREV_SHA" ] && git cat-file -e "${PREV_SHA}^{commit}" 2>/dev/null; then
	LOG="$(git log --no-merges --pretty=format:'%h %s' "${PREV_SHA}..${CURRENT_SHA}" 2>/dev/null || echo '')"
fi
if [ -z "$LOG" ]; then
	LOG="$(git log -1 --pretty=format:'%h %s' "${CURRENT_SHA:-HEAD}" 2>/dev/null || echo '')"
fi

# --- Build the Slack Block Kit payload (Node handles JSON escaping) ---------
# Non-ASCII symbols come from String.fromCharCode so this file stays pure ASCII.
PAYLOAD="$(ENV_LABEL="$ENV_LABEL" SITE_URL="$SITE_URL" WEB_VERSION="$WEB_VERSION" \
	BRANCH="$BRANCH" CURRENT_SHA="$CURRENT_SHA" EMOJI="$EMOJI" LOG="$LOG" node -e '
const e=process.env;
const BULLET=String.fromCharCode(0x2022), DASH=String.fromCharCode(0x2014), ELLIPSIS=String.fromCharCode(0x2026);
const lines=(e.LOG||"").split("\n").filter(Boolean);
// Bucket by Conventional Commit type; newest-first git order is kept per group.
const rank=l=>{const i=l.indexOf(" ");const s=i>0?l.slice(i+1):l;
  return /^feat[(!:]/.test(s)?0:/^fix[(!:]/.test(s)?1:/^docs[(!:]/.test(s)?2:3;};
const fmt=l=>{const i=l.indexOf(" ");const h=i>0?l.slice(0,i):l;const s=i>0?l.slice(i+1):"";return BULLET+" `"+h+"` "+s;};
const TITLES=[":sparkles: *Features*",":bug: *Bugs and Fixes*",":memo: *Docs*",":package: *Other*"];
const groups=[[],[],[],[]];
for(const l of lines)groups[rank(l)].push(fmt(l));
// Full history, never cut: 3000 chars is the Slack limit PER section block, not
// per message, so spread commits across blocks (a message holds up to 50 blocks).
// Each non-empty group renders under its title; the title sticks to the first
// block of the group, oversized groups continue in extra title-less blocks.
const CHUNK=2900, MAX_COMMIT_BLOCKS=46; // 1 deploy-header + 46 commit blocks + 1 overflow tail < 50
const chunks=[];
groups.forEach((g,gi)=>{
  if(!g.length)return;
  let buf=TITLES[gi];
  for(const f of g){
    if(buf.length+1+f.length>CHUNK){chunks.push(buf);buf=f;}else buf+="\n"+f;
  }
  chunks.push(buf);
});
if(!chunks.length)chunks.push("_(no commit range available)_");
if(chunks.length>MAX_COMMIT_BLOCKS){
  const cut=chunks.splice(MAX_COMMIT_BLOCKS);
  const n=cut.reduce((a,c)=>a+c.split("\n").length,0);
  chunks.push(ELLIPSIS+" +"+n+" more");
}
const ver=e.WEB_VERSION?("  `"+e.WEB_VERSION+"`"):"";
const header=e.EMOJI+" *Web deployed "+DASH+" "+e.ENV_LABEL+"*"+ver;
const sub="<"+e.SITE_URL+"|"+e.SITE_URL+">  "+BULLET+"  branch `"+e.BRANCH+"`  "+BULLET+"  `"+String(e.CURRENT_SHA||"").slice(0,7)+"`";
const blocks=[{type:"section",text:{type:"mrkdwn",text:header+"\n"+sub}}];
for(const c of chunks)blocks.push({type:"section",text:{type:"mrkdwn",text:c}});
process.stdout.write(JSON.stringify({blocks}));
' 2>/dev/null || echo '')"

if [ -z "$PAYLOAD" ]; then
	echo "notify-slack: failed to build payload, skipping (deploy unaffected)"
	exit 0
fi

# Local smoke: print the payload instead of posting it.
if [ -n "${NOTIFY_DRY_RUN:-}" ]; then
	printf '%s\n' "$PAYLOAD"
	echo "notify-slack: DRY RUN, not sent"
	exit 0
fi

# --- Send: payload via STDIN (--data-binary @-), never via a CLI arg --------
# Passing $PAYLOAD as a --data argument mangles multibyte chars on some shells
# (msys/Windows codepage). stdin is byte-exact and cross-platform.
if printf '%s' "$PAYLOAD" | curl -fsS --max-time 15 -X POST -H 'Content-Type: application/json' --data-binary @- "$WEBHOOK" >/dev/null 2>&1; then
	echo "notify-slack: sent ($ENV_LABEL${WEB_VERSION:+, $WEB_VERSION})"
else
	echo "notify-slack: WARN delivery failed (non-fatal, deploy unaffected)"
fi

exit 0
